### ISSUE TITLE
From smile DataFrame to spark DataFrame

### ISSUE THREAD

**Issue by damienlancry** [pierrenodet/spark-smile#2]
Hello, 
Nice project! in your readme you show case a way to convert From Spark DataFrame to SMILE DataFrame
I was curious to know if there was a way to do the reverse operation: convert a spark dataframe to a smile dataframe?
or even convert an array of labeledpoints to a smile dataframe.
or even convert an array X of array of doubles + an array y of labels to smile dataframe with a column "class" corresponding to y.

**Comment by pierrenodet** [comment]
Hi, thank you !

Both conversions between SMILE and Spark DataFrame are explained in the README : 

**From Spark DataFrame to SMILE DataFrame**

```scala
import org.apache.spark.smile.implicits._

val mushrooms = spark.read.format("libsvm").load("data/mushrooms.svm")

val smileDF = mushrooms.toSmileDF()
```

**From SMILE DataFrame to Spark DataFrame**

```scala
import org.apache.spark.smile.implicits._

val spark = SparkSession.builder().master("local[*]").getOrCreate()

val mushrooms = read.arff("data/mushrooms.arff").omitNullRows().toSparkDF(spark)

mushrooms.show()
```

To make a dataframe from an Array of Double, you should look at the method "of" in the Smile JavaDoc : 

http://haifengl.github.io/api/java/smile/data/DataFrame.html

Hope it helps, tell me if you have still some troubles !

**Comment by damienlancry** [comment]
Indeed I did not see the of method, that's exactly what I was looking for ! Thanks a lot!
